<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="alexpardilla" failures="1" tests="3" name="mainTest" time="121.350" errors="0" timestamp="2023-06-06T18:25:27 CEST" skipped="0">
  <testcase classname="mainTest" name="runScenario" time="14.658">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at steps.addProdSteps.theUProductAdded(addProdSteps.java:124)
at âœ½.the producte is added(file:///C:/Users/alexp/OneDrive/Escritorio/TFG/TFG-Test/TFG-test/src/test/java/features/addProd.feature:39)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="mainTest" name="runScenario" time="5.261"/>
  <system-out/>
  <testcase classname="mainTest" name="runScenario" time="101.431"/>
  <system-out/>
</testsuite> <!-- mainTest -->
